[default]
CURRENT_ENV = "@jinja {% raw -%} {{this.current_env | lower}} {%- endraw %}" # development or production
HOME_DIR = "@jinja {% raw -%} {{ env.HOME }} {%- endraw %}"
DIR_INPUT="Entrada"
DIR_OUTPUT="Saida"
DEBUG = true
LOG_MONITOR_EC15 = "logs/monitor_{{cookiecutter.project_slug}}.log"